import type { ScopeId } from "./data";
import { policies } from "./policies";
import { awardComparisons, awardSlugs } from "./awards";

export const contentPages: Record<string, { title: string; heading: string; eyebrow: string; description: string; scope?: ScopeId; scoring?: boolean }> = {
  compare: { title: "Messi vs Ronaldo Comparison Explorer", heading: "Compare the records.", eyebrow: "THE COMPARISON EXPLORER", description: "Choose the context, explore the figures, and share what you find. Every comparison keeps its scope and source attached.", scope: "career" },
  goals: { title: "Messi vs Ronaldo Career Goals — Updated 2026", heading: "Career goals.", eyebrow: "THE GOALSCORING STORY", description: "Career goals, non-penalty goals, minutes and scoring rates, updated through 21 September 2026.", scope: "career" },
  "champions-league": { title: "Messi vs Ronaldo Champions League Goals & Assists", heading: "Champions League.", eyebrow: "UEFA CHAMPIONS LEAGUE", description: "Main-competition goals, assists and appearances from UEFA. Qualifying rounds excluded; the different career lengths stay visible.", scope: "champions-league" },
  "la-liga": { title: "Messi vs Ronaldo La Liga Goals & Scoring Rates", heading: "La Liga records.", eyebrow: "THE SPANISH CHAPTER", description: "Their complete La Liga goals and appearances. Explore both total output and goals per appearance, with the same competition boundary.", scope: "la-liga" },
  international: { title: "Messi vs Ronaldo International Goals & Assists — 2026", heading: "Argentina & Portugal.", eyebrow: "INTERNATIONAL FOOTBALL", description: "Argentina and Portugal. Senior international goals and assists through September 2026, including recognized A-international friendlies.", scope: "international" },
  honours: { title: "Messi vs Ronaldo Trophies & Ballon d’Or Awards — 2026", heading: "Trophies & awards.", eyebrow: "TEAM & INDIVIDUAL HONOURS", description: "Team trophies through 2026, plus eight Ballon d’Or awards for Messi and five for Ronaldo. Explore the competitions and counting rules." },
  methodology: { title: "Data Sources, Definitions & Methodology", heading: "Sources & methodology.", eyebrow: "BEHIND EVERY NUMBER", description: "What we count. Where it comes from. What we don’t know. The details that make the numbers worth reading." },
  assists: { title: "Messi vs Ronaldo Career Assists & Goal Contributions", heading: "Assists & goal contributions.", eyebrow: "UNDERSTANDING ASSISTS", description: "Career assists, goal contributions and per-90 production, with provider definitions visible.", scope: "career" },
  "2026": { title: "Messi vs Ronaldo 2026 Goals, Assists & Stats", heading: "2026 statistics.", eyebrow: "2026 · YEAR TO DATE", description: "Goals, assists, appearances and playing minutes from 1 January through 21 September 2026. The year is still in progress.", scope: "2026" },
  "world-cup": { title: "Messi vs Ronaldo World Cup Goals & Assists — 2026", heading: "World Cup records.", eyebrow: "FIFA WORLD CUP", description: "Every World Cup finals appearance, goal and assist through the 2026 tournament. Qualifying games and shootouts are excluded.", scope: "world-cup" },
  "copa-america-vs-euros": { title: "Messi Copa América vs Ronaldo Euros: Goals & Stats", heading: "Copa América & the Euros.", eyebrow: "COPA AMÉRICA / EUROPEAN CHAMPIONSHIP", description: "Messi's Copa América record alongside Ronaldo’s Euros record. Two different tournaments, with their formats and appearances kept visible.", scope: "copa-euros" },
  "head-to-head": { title: "Messi vs Ronaldo Head-to-Head: Goals in Direct Meetings", heading: "Head-to-head meetings.", eyebrow: "DIRECT MEETINGS", description: "Games in which both players appeared: competitive club meetings and senior international friendlies. The 2023 Riyadh exhibition is excluded.", scope: "head-to-head" },
  clubs: { title: "Messi & Ronaldo Club Stats: Inter Miami, Al Nassr & More", heading: "Club career records.", eyebrow: "THE CLUB CHAPTERS", description: "Their current clubs, followed by every first-team club record: goals, assists, appearances and minutes through September 2026.", scope: "current-clubs" },
  penalties: { title: "Messi vs Ronaldo Penalties: Scored, Missed & Conversion", heading: "Penalty records.", eyebrow: "PENALTIES & NON-PENALTY GOALS", description: "Penalty goals, attempts and conversion percentages alongside non-penalty goals. Penalty shootouts are excluded.", scope: "career", scoring: true },
  "free-kicks": { title: "Messi vs Ronaldo Free-Kick Goals & Scoring Breakdown", heading: "Free kicks & goal types.", eyebrow: "FREE KICKS & GOAL TYPES", description: "Direct free kicks, open-play goals from outside the box and the body parts behind their career goals.", scope: "career", scoring: true },
  "hat-tricks": { title: "Messi vs Ronaldo Hat-Tricks & Career Scoring Records", heading: "Career hat-tricks.", eyebrow: "HAT-TRICKS & SCORING RECORDS", description: "Career hat-tricks and goal-type breakdowns. A match with four or five goals still counts as one hat-trick.", scope: "career", scoring: true },
  league: { title: "Messi vs Ronaldo League Goals Across All Clubs", heading: "Domestic league records.", eyebrow: "DOMESTIC LEAGUE CAREERS", description: "Every top-flight domestic league across their club careers. Cups and MLS playoffs are excluded from this league comparison.", scope: "league" },
  "european-clubs": { title: "Messi vs Ronaldo European Club Career Goals & Assists", heading: "European club records.", eyebrow: "EUROPEAN CLUBS", description: "Competitive club careers before Inter Miami and Al Nassr, from Sporting and Barcelona to Manchester, Madrid, Turin and Paris.", scope: "european-clubs" },
  records: { title: "Messi vs Ronaldo Records: The Race to 1,000 Goals", heading: "The race to 1,000 goals.", eyebrow: "CAREER MILESTONES", description: "Career goals and the distance to 1,000. These are present totals, not predictions about when either player will reach the milestone.", scope: "career" },
  about: { title: "About The Rivalry", heading: "About The Rivalry.", eyebrow: "OUR PHILOSOPHY", description: "Two extraordinary careers deserve more than an argument over a single number." },
  contact: { title: "Report a Statistical Correction", heading: "Report a correction.", eyebrow: "CORRECTIONS & FEEDBACK", description: "Found a figure that needs another look? Put the claim and its evidence together in a correction report." },
  credits: { title: "Photography Credits & Licenses", heading: "Photography & credits.", eyebrow: "PHOTOGRAPHY & ATTRIBUTION", description: "Credits for the player portraits, icons and locally hosted fonts used on The Rivalry." },
  ...Object.fromEntries(awardSlugs.map(slug => {
    const award = awardComparisons[slug];
    return [slug, { title: `Messi vs Ronaldo: ${award.label}`, heading: award.label, eyebrow: "INDIVIDUAL AWARDS", description: award.description }];
  })),
  ...policies,
};
