import { publisherConfiguration } from "./publisher-config";
const { analyticsEnabled, adsenseScriptEnabled, adsenseAdsEnabled } = publisherConfiguration(process.env);

export const policyUpdated = "2026-10-02";
export const policyUpdatedLabel = "2 October 2026";

const adminInterfaceCookieDisclosure = "The rivalry-admin-ui cookie lets the browser check whether to show administrator controls. It is readable by JavaScript, expires after eight hours and uses SameSite=Strict and Secure on HTTPS. It does not grant access; the server verifies the separate session cookie. Signing out removes both cookies. Neither cookie is used for advertising or visitor tracking.";
const votingCookieDisclosure = "Opening the fan vote page creates the rivalry-voter cookie, a random browser identifier used to remember one final vote. It is HTTP-only, uses SameSite=Lax and Secure on HTTPS, and is sent only to /api/vote. Its lifetime is up to 400 days, renewed when you load voting results; browsers may remove it sooner. Clearing site data removes this browser’s voting restriction. It is not used for advertising.";
const votingDataDisclosure = "The voting database stores a hash of the random browser identifier, the chosen player and the submission time while the poll operates. It does not collect your name or email. To limit automated voting, a keyed hash of the connecting IP address counts new votes for one hour; expired counters are removed on the next new vote. Raw IP addresses are not stored in the voting database. The publisher’s starting totals are labelled separately from visitor votes.";

type PolicySection = {
  id: string;
  title: string;
  paragraphs: string[];
  links?: { href: string; label: string }[];
};
export type Policy = {
  title: string;
  heading: string;
  eyebrow: string;
  description: string;
  sections: PolicySection[];
};

export const policies: Record<string, Policy> = {
  terms: {
    title: "Terms of Use", heading: "Terms of use.", eyebrow: "USING THE RIVALRY",
    description: "The terms for using our comparisons and articles on messivsronaldo17.com.",
    sections: [
      { id: "about-these-terms", title: "About these terms", paragraphs: ["These terms apply to The Rivalry at messivsronaldo17.com. By using the website, you agree to these terms. If you do not agree, please stop using the website. The Rivalry is an independent football publication; it is not an official service of either player, any club or any football governing body."] },
      { id: "using-the-content", title: "Using the content", paragraphs: ["You may browse our pages and share links. When quoting our original analysis, identify The Rivalry and link to the relevant page so readers can check the context and cutoff date.", "The player photographs and our generated artwork incorporating them are available under CC BY-SA 4.0, as detailed on our Photography and credits page. You may reuse them under that license, including commercially, with the required attribution and ShareAlike terms. Rights in other third-party content, trademarks and provider datasets remain with their respective owners. These terms impose no additional restrictions on the CC-licensed material or uses permitted by applicable law."], links: [{ href: "/credits", label: "Photography and credits" }] },
      { id: "fair-use-of-the-site", title: "Use the website responsibly", paragraphs: ["Do not attempt to access private admin areas without authorization, bypass security controls, introduce malicious code or deliberately overload the service. Do not misrepresent altered content as an unchanged publication from The Rivalry.", "Please send accurate, relevant information when reporting a correction. Do not include passwords, API keys or personal information that is unnecessary to explain the issue."] },
      { id: "statistics-and-availability", title: "Statistics and availability", paragraphs: ["Statistics depend on match coverage, provider definitions and the publication cutoff shown on each page. Totals may change after a match update or correction. A comparison is not a complete assessment of a player, and a missing figure is not necessarily zero.", "We aim to publish accurate, useful information, but do not promise that every figure will be complete, current or error-free, or that the website will always be available. Check the scope and methodology before relying on a figure."], links: [{ href: "/methodology", label: "Read the counting rules" }, { href: "/updates", label: "Published updates" }] },
      { id: "links-and-responsibility", title: "Links and responsibility", paragraphs: ["External links lead to independently operated websites. Their content and terms are their responsibility. Linking to a source does not imply an endorsement or partnership.", "To the extent permitted by applicable law, The Rivalry is not responsible for loss resulting from reliance on website content or an interruption of service. These terms do not exclude liability or rights that cannot lawfully be excluded."] },
      { id: "changes-and-questions", title: "Changes and questions", paragraphs: ["We may revise these terms as the website changes. The date on this page identifies the current version. Questions about the website, permissions or these terms can be raised using the contact information published on our Contact page."], links: [{ href: "/contact", label: "Contact and corrections" }, { href: "/privacy", label: "Privacy policy" }] },
    ],
  },
  privacy: {
    title: "Privacy Policy", heading: "Privacy policy.", eyebrow: "YOUR PRIVACY",
    description: "What The Rivalry stores, why it is used, and the choices available to visitors.",
    sections: [
      { id: "fan-voting", title: "Fan voting", paragraphs: [votingCookieDisclosure, votingDataDisclosure], links: [{ href: "/vote", label: "Fan vote" }] },
      { id: "visiting", title: "Visiting the website", paragraphs: ["The Rivalry publishes football comparisons at messivsronaldo17.com. Public visitors do not need an account. The website does not collect payments or operate newsletter subscriptions.", "Our hosting provider, {0}, receives technical request information needed to deliver and protect the website, which may include an IP address, browser details, requested URL and time of access. Hosting logs are handled according to the provider’s settings and retention practices."] },
      { id: "browser-storage", title: "Preferences and browser storage", paragraphs: ["Your light or dark theme choice is saved in your browser as rivalry-theme. It stays there until you change it, clear site data or your browser removes it. Comparison filters are stored in the URL fragment so that a comparison can be restored or shared.", "On unprefixed pages, we use your browser’s preferred supported language, falling back to English. A link with a language prefix keeps that language. Choosing a language in the menu saves only its language code in the rivalry-locale preference cookie for up to one year. The cookie uses SameSite=Lax and Secure on HTTPS. Clearing it restores automatic browser-language detection.", "Site search matches page titles locally in your browser. We do not send the search text to a search provider. Fonts and licensed player photographs are served with the website; we do not load third-party photo embeds."], links: [{ href: "/cookies", label: "Cookies and local storage" }] },
      { id: "analytics", title: "Website analytics", paragraphs: [analyticsEnabled ? "Vercel Web Analytics is enabled on public pages. It provides aggregate information about page visits, referring websites, approximate location, and browser and device types. It does not use third-party tracking cookies. Vercel uses a temporary visitor identifier that is discarded after 24 hours." : "Vercel Web Analytics is disabled in this edition. Hosting and security request logs are separate from optional visitor analytics.", "When analytics is enabled, our integration removes query strings and URL fragments from the page URL sent to analytics and excludes admin pages. Support form text, names and email addresses are not included in analytics events."], links: [{ href: "https://vercel.com/docs/analytics/privacy-policy", label: "Vercel Web Analytics privacy information" }] },
      { id: "advertising", title: "Advertising", paragraphs: [
        adsenseAdsEnabled ? "Google AdSense is enabled on public pages. Ad availability depends on Google’s approval, your location and your consent choices. Where Google’s consent message is shown, use its Privacy and cookie settings link to revisit your choices." : adsenseScriptEnabled ? "This website loads the Google AdSense script, but ad requests are paused while we prepare consent settings. Loading the script sends Google technical information such as your IP address, browser details and page URL. The script may load Google’s consent message; pausing ads does not prevent these technical requests." : "Advertising is not active on this website. We are preparing for Google AdSense; the following information describes that planned service, not current advertising tracking. An account-verification tag does not display ads or set advertising cookies.",
        "If Google AdSense is activated, third-party vendors, including Google, may use cookies to serve ads based on your previous visits to this website or other websites. Google’s advertising cookies allow Google and its partners to serve ads based on those visits. Advertising requests may also include technical information such as your IP address and browser details.",
        "You can manage Google’s personalized advertising through My Ad Center and learn about other vendors’ opt-out choices at AboutAds. These external choices do not replace any consent controls required on this website. Before advertising starts, this page will identify the active services and explain how to open and change the applicable consent choices.",
        "We will not activate personalized advertising for visitors in the EEA, UK or Switzerland before a Google-certified consent platform is configured and tested. Rejecting personalization must not prevent access to the football content. Non-personalized ads can also use storage and require consent where applicable.",
      ], links: [
        { href: "https://policies.google.com/technologies/partner-sites", label: "How Google uses information from partner sites" },
        { href: "https://myadcenter.google.com/", label: "Google advertising choices" },
        { href: "https://optout.aboutads.info/", label: "Other advertising choices" },
        { href: "/cookies", label: "Cookies and local storage" },
      ] },
      { id: "contact-and-corrections", title: "Contact and correction reports", paragraphs: ["Submitting the Contact form sends your message, category, language, any page or evidence link, and any optional name or email address to our private support inbox. Public visitors cannot read other reports. Authorized administrators use this information to investigate issues, manage corrections and respond when contact details are supplied. We do not use support details for marketing.", "Reports are available for up to 90 days after submission. Expired reports are removed when the support service is next used; administrators can delete reports sooner. Database backups may retain older copies according to the hosting provider’s backup retention. If a correction is published, its statistical evidence can remain in the public revision history without your contact details.", "To limit spam, we use a keyed hash derived from the connecting IP address with a one-hour submission counter and a site-wide 24-hour counter. Expired counters are removed when the support service is next used. The support database does not store the raw IP address. Hosting providers may separately retain request logs. Do not include passwords or sensitive personal information in a report.", "A reference number confirms that the report was saved, not that it has been reviewed or accepted. Email replies are not automatic. If you provide an email address and the publisher replies, the email providers involved handle delivery. Use the Privacy request category to request access, correction or deletion and include your report reference if available."], links: [{ href: "/contact", label: "Contact and corrections" }] },
      { id: "administration", title: "Administration and retention", paragraphs: ["Administrator sign-in uses an essential HTTP-only session cookie, rivalry-admin, with an eight-hour lifetime. Server-side session records support authentication. Provider credentials are encrypted on the server and are not returned to public visitors.", adminInterfaceCookieDisclosure, "Match records and administrative activity are stored in our database so corrections can be reviewed and publication history can be recovered. These records are retained for the archive’s operation and integrity. An administrator’s session expiry is separate from the retention of audit records and backups."] },
      { id: "your-choices", title: "Your choices and questions", paragraphs: ["You can remove saved preferences through your browser’s site-data controls. Removing the admin cookie signs that browser out. Blocking storage may prevent preferences or administrator sign-in from working, but public comparisons do not require a visitor account.", "Depending on the laws that apply to you, you may have rights to request access, correction or deletion of personal information, or to object to some uses. Use the contact details published on our Contact page for privacy questions. You may also raise a concern with the relevant data protection authority."], links: [{ href: "/contact", label: "Contact information" }] },
      { id: "external-services-and-changes", title: "External websites and changes", paragraphs: ["Links to football sources and photography credits take you to other websites with their own privacy practices. This policy describes the current website. We will update it when services or information-handling practices change."] },
    ],
  },
  cookies: {
    title: "Cookie Policy", heading: "Cookies & local storage.", eyebrow: "BROWSER PREFERENCES",
    description: "A short inventory of the storage used by this edition of the website.",
    sections: [
      { id: "fan-voting", title: "Fan voting", paragraphs: [votingCookieDisclosure], links: [{ href: "/privacy#fan-voting", label: "Read the privacy policy" }] },
      { id: "theme-preference", title: "Your theme preference", paragraphs: ["The rivalry-theme local-storage entry remembers whether you chose the light or dark theme. Local storage is different from a cookie: this preference stays in your browser and is not automatically attached to every request. It has no fixed expiry and can be removed through your browser’s site-data settings."] },
      { id: "language-preference", title: "Your language preference", paragraphs: ["On unprefixed pages, we use your browser’s preferred supported language, falling back to English. A link with a language prefix keeps that language. Choosing a language in the menu saves only its language code in the rivalry-locale preference cookie for up to one year. The cookie uses SameSite=Lax and Secure on HTTPS. Clearing it restores automatic browser-language detection."] },
      { id: "admin-session", title: "Administrator session", paragraphs: ["The rivalry-admin cookie is used only for administrator sign-in. It identifies an authenticated session and expires after eight hours. It is HTTP-only, uses SameSite=Strict, and is marked Secure on the HTTPS production website. It is not an advertising or visitor-tracking cookie.", adminInterfaceCookieDisclosure] },
      { id: "other-features", title: "Search, filters and third parties", paragraphs: ["Search runs locally. Comparison filters can appear after the # symbol in a shared URL; those fragments are not sent as part of an HTTP request to the server. Submitting a support report does not create a tracking cookie.", adsenseScriptEnabled ? "Vercel Web Analytics, when enabled, uses no third-party tracking cookies. Google’s AdSense script is loaded on public pages; see the Advertising section of our Privacy policy for its current status and consent information. No third-party photo embeds are loaded. External websites may use their own cookies after you follow a link to them." : "Vercel Web Analytics, when enabled, uses no third-party tracking cookies. No advertising scripts, advertising cookies or third-party photo embeds are active in this edition. External websites may use their own cookies after you follow a link to them."] },
      { id: "manage-storage", title: "Managing stored preferences", paragraphs: ["Use your browser’s settings to inspect or remove site data for messivsronaldo17.com. Clearing local storage resets your theme preference. Clearing the admin session cookie signs you out if you are an administrator. If the site introduces additional storage technologies, this inventory will be updated."], links: [{ href: "/privacy", label: "Read the privacy policy" }] },
    ],
  },
  disclaimer: {
    title: "Editorial & Data Disclaimer", heading: "Context matters.", eyebrow: "EDITORIAL & DATA DISCLAIMER",
    description: "How to interpret our figures, photography and relationship to the people in the comparison.",
    sections: [
      { id: "independent-publication", title: "An independent publication", paragraphs: ["The Rivalry is not affiliated with, endorsed by or operated by Lionel Messi, Cristiano Ronaldo, their clubs, national associations, UEFA or FIFA. Names, photographs and competition references identify the subjects being discussed. They do not imply an official relationship."] },
      { id: "coverage-and-cutoffs", title: "Coverage and cutoff dates", paragraphs: ["A statistic is meaningful within its stated competition, date range and counting rules. The website combines a reviewed baseline with published match updates. Some detailed categories have a different cutoff when current provider data is unavailable. The website is not a guaranteed real-time match feed.", "Definitions can differ between providers, especially for assists, appearances and team honours. Overlapping categories should not be added together. Figures and calculations may be corrected as better evidence becomes available."], links: [{ href: "/methodology", label: "Sources and methodology" }, { href: "/updates", label: "Public update log" }] },
      { id: "comparison-and-opinion", title: "Comparison and opinion", paragraphs: ["A star identifies the leader in a particular statistic according to the displayed rules. It is not a judgment of who is the better player overall. Articles provide interpretation and context; readers may reasonably reach different conclusions."] },
      { id: "photographs-and-corrections", title: "Photography and corrections", paragraphs: ["Player photographs are by Bryan Berlin / WikiPortraits and are licensed under CC BY-SA 4.0. Our Photography credits page identifies each source, crop and adaptation and explains the license terms for reuse. Other third-party material retains its own rights and terms. Please use the contact information on the website for a rights concern or a proposed correction."], links: [{ href: "/credits", label: "Photography credits" }, { href: "/contact", label: "Contact and corrections" }] },
    ],
  },
  accessibility: {
    title: "Accessibility Statement", heading: "Football for everyone.", eyebrow: "ACCESSIBILITY",
    description: "How we support accessible browsing, and how to describe a problem when something gets in the way.",
    sections: [
      { id: "our-approach", title: "Our approach", paragraphs: ["We aim to make The Rivalry usable with a keyboard, screen reader and browser zoom, on both large and small screens. Accessibility is an ongoing part of development. This statement is not a claim of independent certification or complete conformance."] },
      { id: "browsing-tools", title: "Tools available on the website", paragraphs: ["A Skip to content link appears when you navigate with the keyboard. Main menus and custom selectors support keyboard interaction. The header includes a light and dark theme switch, and comparison values are provided as text in addition to visual bars.", "Player photographs include text alternatives. Comparison controls have accessible labels, and table headings identify the data. Charts with a data disclosure offer a text-based way to inspect the underlying figures."] },
      { id: "known-limitations", title: "Limitations and testing", paragraphs: ["Dense comparison tables may need horizontal scrolling on small screens. Third-party websites linked as sources have their own interfaces, which we do not control. Automated checks help us find common problems, but do not replace testing by people using assistive technology."] },
      { id: "report-a-barrier", title: "Report an access problem", paragraphs: ["Use the Accessibility problem category on our Contact form to describe a barrier. Include the page URL, what you were trying to do, the device and browser, and any assistive technology involved. Please leave out private account details."], links: [{ href: "/contact", label: "Contact information" }, { href: "/sitemap", label: "Browse the site map" }] },
    ],
  },
};
