import { test, expect, type Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import sharp from "sharp";
test.use({ actionTimeout: 15_000 });
const origin = "http://localhost:3002";
async function signIn(page: Page) {
  await page.goto("/admin/blog"); await page.getByLabel("Email address", {exact:true}).fill("admin@example.com");
  await page.getByLabel("Admin password").fill("integration-test-password-only");
  await page.getByRole("button", { name: "Sign in to dashboard" }).click();
  await expect(page.getByRole("heading", { name: "Blog editor" })).toBeVisible();
  await expect(page.getByRole("button", { name: "New article", exact: true }).first()).toBeEnabled();
}
test("blog APIs protect drafts and uploads with authentication, origin checks and size limits", async ({ request, page }) => {
  expect((await request.get("/api/admin/blog")).status()).toBe(401);
  for (const route of ["/api/admin/blog", "/api/admin/blog/images"]) expect((await request.post(route, { headers: { origin }, data: {} })).status()).toBe(401);
  await signIn(page);
  for (const route of ["/api/admin/blog", "/api/admin/blog/images"]) expect((await page.request.post(route, { headers: { origin: "https://attacker.example" }, data: {} })).status()).toBe(403);
  expect((await page.request.post("/api/admin/blog/images", { headers: { origin, "content-type": "image/svg+xml" }, data: "<svg/>" })).status()).toBe(415);
  expect((await page.request.post("/api/admin/blog/images", { headers: { origin, "content-type": "image/png" }, data: "not a real PNG" })).status()).toBe(422);
  expect((await page.request.post("/api/admin/blog", { headers: { origin, "content-type": "application/json" }, data: "x".repeat(750_001) })).status()).toBe(413);
  expect((await page.request.get("/api/admin/blog?locale=xx")).status()).toBe(400);
  expect((await page.request.get("/api/admin/blog")).headers()["cache-control"]).toBe("private, no-store");
});

test("admin writes, formats, uploads, previews, publishes, edits and deletes a localized article", async ({ page, browser }, info) => {
  test.setTimeout(120_000);
  const errors: string[] = []; page.on("pageerror", error => errors.push(error.message));
  await signIn(page);
  await page.screenshot({ path: `.artifacts/blog-library-${info.project.name}.png` });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const libraryAudit = await new AxeBuilder({ page }).include('[aria-label="Article library"]').analyze();
  expect(libraryAudit.violations.map(item => item.id)).toEqual([]);
  await page.getByRole("combobox",{name:"Article language",exact:true}).click(); await page.getByRole("option",{name:"Español",exact:true}).click();
  await expect(page.getByRole("button", { name: "New article", exact: true }).first()).toBeEnabled();
  await page.getByRole("button", { name: "New article", exact: true }).first().click();
  const slug = `editor-${info.project.name}-${Date.now()}`;
  const title = `Prueba editorial ${info.project.name}`;
  await page.getByLabel("Article title", { exact: true }).fill(title);
  if (page.viewportSize()!.width <= 900) {
    await expect(page.getByLabel("Article language")).toBeHidden();
    await page.getByRole("button", { name: "Browse articles" }).click();
    await expect(page.getByLabel("Article language")).toBeVisible();
    await page.getByRole("button", { name: "Hide articles" }).click();
    await expect(page.getByLabel("Article title", { exact: true })).toHaveValue(title);
  }
  await page.getByLabel("URL slug", { exact: true }).fill(slug);
  await page.getByLabel("Excerpt / search description").fill("Un artículo de prueba aislado para comprobar el editor.");
  const body = page.getByRole("textbox", { name: "Article body", exact: true });
  await body.fill("Original article body for publishing tests.");
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: `.artifacts/blog-writing-${info.project.name}.png` });
  await body.press("ControlOrMeta+a"); await page.getByRole("button", { name: "Bold", exact: true }).click();
  await page.getByRole("button", { name: "Add or edit link" }).click();
  await page.getByLabel("Link URL", { exact: true }).fill("https://example.com/evidence"); await page.getByRole("button", { name: "Apply link" }).click();
  await page.getByRole("button", { name: "Add cover image" }).click();
  const image = await sharp({ create: { width: 240, height: 140, channels: 3, background: "#668a32" } }).png().toBuffer();
  await page.getByLabel("Image file", { exact: true }).setInputFiles({ name: "test-cover.png", mimeType: "image/png", buffer: image });
  await page.getByLabel("Image description (alt text)", { exact: true }).fill("Synthetic green cover image");
  await page.getByLabel("Caption / photo credit (optional)").fill("Synthetic test image");
  await page.getByRole("button", { name: "Upload image", exact: true }).click();
  await expect(page.getByLabel("Cover image alt text")).toHaveValue("Synthetic green cover image");
  const mediaPath = await page.locator('img[alt="Synthetic green cover image"]').getAttribute("src");
  await page.getByRole("button", { name: "Preview", exact: true }).click();
  await expect(page.locator("strong").filter({ hasText: "Original article body" })).toBeVisible();
  await expect(page.getByRole("link", { name: "Original article body for publishing tests." })).toHaveAttribute("href", "https://example.com/evidence");
  await page.getByRole("button", { name: "Continue editing" }).click();
  await expect(body).toContainText("Original article body");
  await page.getByRole("button", { name: "Save draft", exact: true }).click();
  await expect(page.getByLabel("URL slug", { exact: true })).toBeDisabled();
  await expect(page.getByText("Unsaved changes", { exact: true })).toHaveCount(0);
  const visitor = await browser.newContext({ baseURL: origin }); const publicPage = await visitor.newPage();
  expect((await visitor.request.get(`/es/insights/${slug}`)).status()).toBe(404);
  expect((await visitor.request.get(mediaPath!)).status()).toBe(404);
  expect((await page.request.get(mediaPath!)).headers()["content-type"]).toBe("image/webp");
  const before = (await (await page.request.get("/api/admin/blog?locale=es")).json()).posts.find((post: { slug: string }) => post.slug === slug);
  await page.getByRole("button", { name: "Publish article", exact: true }).click();
  await expect(page.getByRole("link", { name: "View live" })).toBeVisible();
  await publicPage.goto(`/es/insights/${slug}`);
  await expect(publicPage.getByRole("heading", { level: 1 })).toHaveText(title);
  await expect(publicPage.locator("article strong").filter({ hasText: "Original article body" })).toBeVisible();
  await expect(publicPage.locator("article time")).not.toHaveText("");
  await expect(publicPage.locator('link[rel="alternate"][hreflang="es"]')).toHaveCount(1);
  await expect(publicPage.locator('link[rel="alternate"][hreflang="en"]')).toHaveCount(0);
  expect((await visitor.request.get(`/insights/${slug}`)).status()).toBe(404);
  const publicImage = await visitor.request.get(mediaPath!);
  expect(publicImage.headers()["content-type"]).toBe("image/webp");
  expect(publicImage.headers()["cache-control"]).toBe("private, no-store");
  expect(await (await visitor.request.get(mediaPath!)).body()).toEqual(await publicImage.body());
  expect(await (await visitor.request.get("/sitemap.xml")).text()).toContain(`/es/insights/${slug}`);
  await publicPage.goto("/es/insights"); await expect(publicPage.locator(`.editorial-card[href="/es/insights/${slug}"]`)).toBeVisible();
  await publicPage.getByRole("button", { name: /Search the site|Buscar en el sitio/ }).click();
  await expect(publicPage.locator(`dialog a[href="/es/insights/${slug}"]`)).toBeVisible();
  await page.getByLabel("Article title", { exact: true }).fill(`${title} revisada`);
  await page.getByRole("button", { name: "Save draft", exact: true }).click();
  await expect(page.getByText("Unsaved changes", { exact: true })).toHaveCount(0);
  await publicPage.goto(`/es/insights/${slug}`); await expect(publicPage.getByRole("heading", { level: 1 })).toHaveText(title);
  const stale = await page.request.post("/api/admin/blog", { headers: { origin }, data: { id: before.id, locale: "es", slug, revision: before.revision, action: "publish", draft: before.draft } });
  expect(stale.status()).toBe(409);
  await page.getByRole("button", { name: "Publish changes", exact: true }).click();
  await expect(page.getByText("Unpublished changes", { exact: true })).toHaveCount(0);
  await publicPage.reload(); await expect(publicPage.getByRole("heading", { level: 1 })).toHaveText(`${title} revisada`);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const audit = await new AxeBuilder({ page }).include('[aria-label="Article editor"]').analyze(); expect(audit.violations.map(item => item.id)).toEqual([]);
  await page.screenshot({ path: `.artifacts/blog-editor-${info.project.name}.png`, fullPage: true });
  page.once("dialog", dialog => dialog.accept()); await page.getByRole("button", { name: "Move to Trash" }).click();
  await expect(page.getByRole("button", { name: "Restore as draft" })).toBeVisible();
  expect((await visitor.request.get(`/es/insights/${slug}`)).status()).toBe(404);
  expect((await visitor.request.get(mediaPath!)).status()).toBe(404);
  // Cached bytes remain available to the admin, but must not bypass visibility.
  expect((await page.request.get(mediaPath!)).status()).toBe(200);
  expect((await visitor.request.get(mediaPath!)).status()).toBe(404);
  expect(await (await visitor.request.get("/sitemap.xml")).text()).not.toContain(`/es/insights/${slug}`);
  await page.getByRole("button", { name: "Restore as draft" }).click();
  await expect(page.getByRole("button", { name: "Publish article", exact: true })).toBeVisible();
  await expect(page.getByLabel("Article title", { exact: true })).toHaveValue(`${title} revisada`);
  expect((await visitor.request.get(`/es/insights/${slug}`)).status()).toBe(404);
  await visitor.close(); expect(errors).toEqual([]);
});

test("inline images, tables, Arabic drafts and unsaved changes survive preview", async ({ page }) => {
  test.setTimeout(90_000);
  await signIn(page); await page.getByRole("combobox",{name:"Article language",exact:true}).click(); await page.getByRole("option",{name:"العربية",exact:true}).click();
  await expect(page.getByRole("button", { name: "New article", exact: true }).first()).toBeEnabled();
  await page.getByRole("button", { name: "New article", exact: true }).first().click();
  await page.getByLabel("Article title", { exact: true }).fill("تحليل كرة القدم");
  await page.getByLabel("URL slug", { exact: true }).fill(`arabic-${Date.now()}`);
  await page.getByRole("textbox", { name: "Article body", exact: true }).fill("مقال تجريبي خاص لاختبار محرر المقالات.");
  await page.getByRole("button", { name: "Insert table", exact: true }).click();
  await expect(page.locator(".tiptap table")).toHaveCount(1);
  await page.getByRole("button", { name: "Add row", exact: true }).click(); await expect(page.locator(".tiptap table tr")).toHaveCount(4);
  await page.getByRole("button", { name: "Remove table", exact: true }).click();
  await page.getByRole("textbox", { name: "Article body", exact: true }).press("ControlOrMeta+End");
  await page.getByRole("button", { name: "Insert image", exact: true }).click();
  const image = await sharp({ create: { width: 60, height: 40, channels: 3, background: "#aabbcc" } }).png().toBuffer();
  await page.getByLabel("Image file", { exact: true }).setInputFiles({ name: "inline.png", mimeType: "image/png", buffer: image });
  await page.getByLabel("Image description (alt text)", { exact: true }).fill("A synthetic inline image");
  await page.getByRole("button", { name: "Upload image", exact: true }).click();
  await expect(page.locator(".tiptap img")).toHaveCount(1);
  if (await page.getByRole("button",{name:"Open admin navigation"}).isVisible()) await page.getByRole("button",{name:"Open admin navigation"}).click();
  page.once("dialog", dialog => dialog.dismiss()); await page.getByRole("link", { name: "Overview", exact: true }).filter({visible:true}).click();
  if (await page.getByRole("button",{name:"Close admin navigation"}).isVisible()) await page.getByRole("button",{name:"Close admin navigation"}).click();
  await expect(page).toHaveURL(/\/admin\/blog$/);
  await page.getByRole("button", { name: "Preview", exact: true }).click(); await expect(page.getByRole("img", { name: "A synthetic inline image" })).toBeVisible();
  await page.getByRole("button", { name: "Continue editing" }).click(); await expect(page.locator(".tiptap img")).toHaveCount(1);
  await page.getByRole("button", { name: "Save draft", exact: true }).click(); await expect(page.getByText("Unsaved changes", { exact: true })).toHaveCount(0);
  await page.reload(); await page.getByRole("combobox",{name:"Article language",exact:true}).click(); await page.getByRole("option",{name:"العربية",exact:true}).click(); await page.getByRole("button", { name: /تحليل كرة القدم/ }).first().click();
  await expect(page.locator(".tiptap img")).toHaveCount(1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
