import { getI18n } from "@/lib/i18n/server";
import Link from "@/components/localized-link";
import { getPublishedData } from "@/lib/server-data";
import { readRecords } from "@/lib/admin/database";
import { pageMetadata } from "@/lib/site";
export async function generateMetadata() { return pageMetadata("Published match updates", "Dated Messi and Ronaldo match records added after the reviewed baseline, with sources and coverage notes.", "/updates"); }
export default async function UpdatesPage() {
    const { t } = await getI18n();
    const data = await getPublishedData();
    const records = (await readRecords()).sort((a, b) => b.date.localeCompare(a.date));
    return <div className="page-container inner-page"><section className="page-intro"><div><span className="eyebrow">{t("A RECORD OF EVERY CHANGE")}</span><h1>{t("Published updates")}<span className="heading-dot">.</span></h1><p>{t("The matches behind the latest totals.")}</p></div></section><div className="prose panel"><h2>{t("Coverage and counting rules")}</h2><p>{t("The reviewed baseline ends {0}. The records below are added to that baseline. An unlisted date has not been verified; this page is not a complete historical match log. Automatic imports use API-Football\u2019s assist definition, which can differ from the baseline provider. Goal-type breakdowns retain their displayed baseline cutoff.", { "0": t(data.baselineDate) })}</p><p>{t("Only senior competitive club matches and senior internationals are included. Club friendlies and shootout kicks are excluded. League totals exclude MLS playoffs. Manual corrections take precedence over automatic imports.")}</p><Link href="/methodology">{t("Read the baseline methodology \u2197")}</Link></div><div className="panel admin-table-wrap"><table className="admin-table"><caption>{t("Published match records after {0}", { "0": t(data.baselineDate) })}</caption><thead><tr><th>{t("Date (UTC)")}</th><th>{t("Player / match")}</th><th>{t("Goals")}</th><th>{t("Assists")}</th><th>{t("Minutes")}</th><th>{t("Evidence")}</th></tr></thead><tbody>{records.map(r => <tr key={r.id}><td>{t(r.date)}</td><th scope="row">{t(r.player === "messi" ? "Messi" : "Ronaldo")}<small>{t("{0} vs {1} \u00B7 {2}", { "0": t(r.team), "1": t(r.opponent), "2": t(r.competition) })}</small></th><td>{t(r.goals)}</td><td>{t(r.assists)}</td><td>{t(r.minutes)}</td><td><a href={r.source} target="_blank" rel="noreferrer">{t(r.provider === "manual" ? "Manual correction" : "API-Football")} ↗</a><small>{t(r.note)}</small></td></tr>)}</tbody></table>{!records.length && <p className="admin-empty">{t("No matches have been added after the baseline yet. Current public totals remain the reviewed snapshot.")}</p>}</div></div>;
}
